// <auto-generated />
using System;
using MaintenancePro2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaintenancePro2.Migrations
{
    [DbContext(typeof(theContext))]
    [Migration("20220922233207_FreshMigration")]
    partial class FreshMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MaintenancePro2.Models.MaintenanceItem", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MotorID")
                        .HasColumnType("int");

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("interval")
                        .HasColumnType("float");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("note")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime(6)");

                    b.HasKey("itemID");

                    b.HasIndex("MotorID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("MaintenancePro2.Models.Motor", b =>
                {
                    b.Property<int>("motorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("hours")
                        .HasColumnType("float");

                    b.Property<string>("make")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("motorID");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("MaintenancePro2.Models.PreformedItem", b =>
                {
                    b.Property<int>("preformedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("MotorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdat")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dpa")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("hpa")
                        .HasColumnType("float");

                    b.Property<DateTime>("updatedat")
                        .HasColumnType("datetime(6)");

                    b.HasKey("preformedID");

                    b.HasIndex("ItemID");

                    b.ToTable("PerformedItems");
                });

            modelBuilder.Entity("MaintenancePro2.Models.MaintenanceItem", b =>
                {
                    b.HasOne("MaintenancePro2.Models.Motor", "Bike")
                        .WithMany("motorItems")
                        .HasForeignKey("MotorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaintenancePro2.Models.PreformedItem", b =>
                {
                    b.HasOne("MaintenancePro2.Models.MaintenanceItem", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
